funflow/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from debug_toolbar.toolbar import debug_toolbar_urls 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('idea.urls')),
    path('', include('account.urls')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT})
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += debug_toolbar_urls()

idea/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page

from . import views


urlpatterns = [
    path('', cache_page(60*15)(views.Index.as_view()), name='index'),
    path('search/', views.search_ideas, name='search_results'),
    path('idea_detail/<int:idea_id>/', views.IdeaDetail.as_view(), name='idea'),
    path('idea_detail/<int:idea_id>/comment/', views.AddComment .as_view(), name='add_comment'),
    path('category/<slug:category_slug>/', views.IdeaCategory.as_view(), name='category'),
    path('categories/', views.categories, name='categories'),
    path('add_idea/', views.AddIdea.as_view(), name='add_idea'),
    path('about/', views.about, name='about'),
]

idea/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings
from django.urls import reverse


class User(AbstractUser):
    avatar = models.ImageField(upload_to="avatars/%Y/%m/%d/", null=True, blank=True, editable=True)
    email = models.EmailField(max_length=254, unique=True, editable=True)
    about_me = models.TextField(max_length=500, blank=True, editable=True)

    def __str__(self):
        return self.username

class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)

    def __str__(self):
        return self.name

class Idea(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    time_create = models.DateTimeField(auto_now_add=True)
    time_update = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    category = models.ForeignKey('Category', null=True, on_delete=models.PROTECT)

    class Meta:
        ordering = ['-time_create']
        
    def get_absolute_url(self):
        return reverse("idea", kwargs={"idea_id": self.pk})

    def __str__(self):
        return self.title

class Comment(models.Model):
    class Score(models.IntegerChoices):
        УЖАСНО = 1
        ПЛОХО = 2
        НОРМАЛЬНО = 3
        ХОРОШО = 4
        ОТЛИЧНО = 5
    
    class Meta:
        ordering = ['-time_create']
    
    score = models.IntegerField(choices=Score.choices)
    text = models.TextField(blank=False)
    time_create = models.DateTimeField(auto_now_add=True)
    time_update = models.DateTimeField(auto_now=True)
    idea = models.ForeignKey('Idea', null=True, on_delete=models.SET_NULL)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.pk)

idea/forms.py
from django import forms
from .models import *

class AddIdeaForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].empty_label = 'Категория не выбрана'

    class Meta:
        model = Idea
        fields = ['title', 'description', 'category']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'}),
            'description': forms.Textarea(attrs={'cols': 60, 'rows': 10}),
        }

class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text', 'score']
        widgets = {
            'text': forms.Textarea(attrs={'cols': 60, 'rows': 10}),
        }

idea/views.py
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseNotFound
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from django.views.decorators.cache import cache_page

from .models import Idea, Category, Comment
from .forms import AddIdeaForm, AddCommentForm
from .utils import DataMixin


class Index(DataMixin, ListView):
    model = Idea
    template_name = 'idea/index.html'
    context_object_name = 'ideas'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Главная страница')
        return dict(list(context.items()) + list(c_def.items()))


class IdeaDetail(DataMixin, DetailView):
    model = Idea
    template_name = 'idea/idea_detail.html'
    context_object_name = 'idea'
    pk_url_kwarg = 'idea_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = AddCommentForm()  # Передаем форму в контекст
        c_def = self.get_user_context(title=Idea.objects.get(
            id=self.kwargs['idea_id']))
        context['comments'] = Comment.objects.filter(idea_id=self.object.pk)
        context['score'] = Comment.Score.choices
        return dict(list(context.items()) + list(c_def.items()))


class AddComment(LoginRequiredMixin, CreateView):
    form_class = AddCommentForm
    model = Comment
    template_name = 'idea/idea_detail.html'
    login_url = reverse_lazy('login')  # Переход на страницу логина, если не авторизован
    pk_url_kwarg = 'idea_id'

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.idea = get_object_or_404(Idea, pk=self.kwargs['idea_id'])
        form.save()
        messages.success(self.request, 'Комментарий добавлен')
        return redirect('idea', idea_id=form.instance.idea.pk)

    def form_invalid(self, form):
        idea = get_object_or_404(Idea, pk=self.kwargs['idea_id'])
        context = self.get_context_data(object=idea)
        context['form'] = form
        return self.render_to_response(context)


def categories(request):
    categories = Category.objects.all()

    context = {
        'categories': categories,
        'title': 'Список категорий',
    }

    return render(request, 'idea/categories.html', context=context)

class IdeaCategory(DataMixin, ListView):
    model = Idea
    template_name = 'idea/category.html'
    slug_url_kwarg = 'category_slug'
    context_object_name = 'ideas'
    allow_empty = False
    
    def get_queryset(self):
        return Idea.objects.filter(category__slug=self.kwargs['category_slug'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        category = get_object_or_404(Category, slug=self.kwargs['category_slug'])
        c_def = self.get_user_context(title=f"Категория - {category.name}")
        return dict(list(context.items()) + list(c_def.items()))

class AddIdea(DataMixin, LoginRequiredMixin, CreateView):
    form_class = AddIdeaForm
    template_name = 'idea/add_idea.html'
    success_url = reverse_lazy('index')
    login_url = reverse_lazy('index')
    raise_exception = True

    def form_valid(self, form):
        instance = form.instance
        instance.author_id = self.request.user.id
        instance.title = self.request.POST['title']
        instance.description = self.request.POST['description']
        instance.category = Category.objects.get(id=int(self.request.POST['category']))
        form.save()
        messages.success(self.request, 'Идея добавлена')
        return super().form_valid(form)
    

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Добавить идею')

        return dict(list(context.items()) + list(c_def.items()))


def search_ideas(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        ideas = Idea.objects.filter(
            Q(title__contains=searched) | Q(description__contains=searched))
        context = {
            'title': f"Поиск - {searched}",
            'ideas': ideas,
            'categories': Category.objects.all(),
        }
        return render(request, 'idea/search_results.html', context)
    else:
        return render(request, 'idea/search_results.html', {})
    
def about(request):
    categories = Category.objects.all()
    context = {
        'title': 'О нас',
        'categories': categories,
    }

    return render(request, 'idea/about.html', context)

def pageNotFound(request, exception):
    return HttpResponseNotFound('<h1>Страница не найдена</h1>')

idea/templates/idea/about.html
{% extends "idea/base.html" %}

{% block content %}
<div class="container">   
    <h1 class="mt-5">Добро пожаловать в FunFlow</h1><p> — ваше идеальное место для поиска вдохновения и идей для свободного времени!</p>
        <p class="lead"> Мы понимаем, как сложно иногда найти интересное занятие, когда есть свободные часы. Современная жизнь полна стрессов, и каждому из нас необходимо время, чтобы расслабиться, заняться любимым делом или попробовать что-то новое. Именно поэтому мы создали FunFlow — платформу, которая помогает вам легко и быстро находить развлечения и увлечения, подходящие именно вам.
    
            <h1>Что мы предлагаем?</h1>
            
            В FunFlow вы найдете разнообразные идеи для проведения свободного времени: от увлекательных хобби до необычных мероприятий, от спокойного отдыха до активного времяпрепровождения. Независимо от того, сколько у вас свободного времени — несколько минут или целый выходной, мы поможем вам найти что-то интересное и полезное.
            <h1>Наши ценности</h1>
            <ul>
                <li>
            Индивидуальный подход: Мы знаем, что каждый человек уникален, и наши идеи созданы для того, чтобы удовлетворить самые разные интересы и предпочтения. Хотите расслабиться за чтением книги, научиться готовить экзотическое блюдо или провести день на природе? FunFlow предложит вам идеи, которые подойдут именно вам.
                </li>
            Качество и креативность: Мы стремимся предлагать только самые лучшие и интересные идеи. Наша команда регулярно обновляет и добавляет новый контент, чтобы вы всегда могли найти что-то свежее и увлекательное.
                <li>
            Сообщество: FunFlow — это не просто набор идей, это место, где пользователи могут делиться своими находками, оставлять отзывы и вдохновлять друг друга. В нашем сообществе вы сможете не только найти идеи, но и поделиться своими впечатлениями, помочь другим людям найти что-то по душе.
                </li>
            </ul>
            <h1>Почему мы?</h1>
            
            Мы верим, что каждый заслуживает того, чтобы получать удовольствие от жизни, независимо от того, сколько у него свободного времени. FunFlow создан для того, чтобы помочь вам сделать ваш досуг насыщенным и запоминающимся. Мы стремимся к тому, чтобы каждое ваше свободное мгновение было наполнено радостью, новыми открытиями и приятными эмоциями.
            
            Присоединяйтесь к FunFlow и позвольте нам помочь вам сделать ваше свободное время по-настоящему интересным и ярким!</p>
</div>
{% endblock content %}

idea/templates/idea/add_idea.html
{% extends "idea/base.html" %}

{% block content %}
<div class="container">
<form action="{% url 'add_idea' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="mb-3" style="width: 30rem;">
        <label for="{{ form.title.id_for_label }}" class="form-label">Идея</label>
        <input name="title" class="form-control" id="exampleFormControlInput2" rows="3"></input>
      </div>
    <div class="mb-3" style="width: 30rem;">
        <label for="{{ form.description.id_for_label }}" class="form-label">Описание</label>
        <textarea name="description" class="form-control" id="exampleFormControlTextarea" rows="3"></textarea>
      </div>
      <select name="category" class="form-select" style="width: 30rem;">
        <option selected>Выбери категорию</option>
        {% for cat in categories %}
        <option value="{{ cat.id }}">{{ cat.name }}</option>
        {% endfor %}
      </select>

    <button type="submit" class="btn btn-dark" style="margin-top: 15px;">Отправить</button>
</form>
</div>
{% endblock content %}  

idea/templates/idea/base.html
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{{ title }}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static "css/styles.css" %}" type="text/css">
        <link rel="shortcut icon" href="{% static 'images/funflow.ico' %}" type="image/x-icon"/>
    </head>
    <body>
        <header class="p-3 text-bg-dark" data-bs-theme="dark">
          <div class="container">
          <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
              <img src="{% static 'images/funflow.ico' %}" width="40px">
            </a>
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
              <li><a href="{% url 'index' %}" class="nav-link px-2 text-white">Главная</a></li>
              <li><a href="{% url 'add_idea' %}" class="nav-link px-2 text-white">Предложить идею</a></li>          
              <div class="dropdown">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white" href="#" id="dropdown04" data-bs-toggle="dropdown" aria-expanded="false">Категории</a>
                    <ul class="dropdown-menu" aria-labelledby="dropdown04">
                        {% for cat in categories %}
                        <li><a class="dropdown-item" href="{% url 'category' cat.slug %}">{{ cat.name }}</a></li>
                        {% endfor %}
                    </ul>
                  </li>
              </div>
              <li><a href="{% url 'about' %}" class="nav-link px-2 text-white">О нас</a></li>
            </ul>
            <form action="{% url 'search_results' %}" class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3 d-flex" role="search" method="POST">
              {% csrf_token %}
              <input name="searched" type="search" class="form-control me-2 form-control-dark text-bg-dark" placeholder="Поиск..." label="Поиск">
              <button class="btn btn-outline-secondary" type="submit">Поиск</button>
            </form>
            <div class="text-end">
              {% if request.user.is_authenticated %}
                  <div class="dropdown text-end">
                    <a href="#" class="d-block link-light text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                      {% if request.user.avatar %}
                        <img src="{{ request.user.avatar.url }}" alt="mdo" width="32" height="32" class="rounded-circle">
                      {% else %}
                        <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="white" class="bi bi-person-fill" viewBox="0 0 16 16">
                          <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
                        </svg>
                      {% endif %}
                      </a>
                    <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser">
                      <li><a class="dropdown-item" href="{% url 'profile' request.user.username %}">Мой профиль</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{% url 'logout' %}">Выйти</a></li>
                    </ul>
                  </div>
                  {% else %}
                    <a href="{% url 'login' %}"><button type="button" class="btn btn-outline-light me-2">Войти</button></a>
                    <a href="{% url 'register' %}"><button type="button" class="btn btn-warning">Регистрация</button></a>
              {% endif %}
            </div>
          </div>
        </div>
      </header>
        <!-- Button HTML (to Trigger Modal) -->
        {% if messages %}
        <div class="alert alert-success" role="alert">
        <ul class="messages">
          {% for message in messages %}
            <li class="{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</li>
          {% endfor %}</p>
        </ul>
      </div>
        {% endif %}
  {% block content %}{% endblock content %}
    <nav aria-label="Page navigation example">
      {% if page_obj.has_other_pages %}
        <ul class="pagination justify-content-center">
          {% if page_obj.has_previous %}
            <li class="page-item">
              <a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo;</a>
            </li>
          {% endif %}
          {% for p in paginator.page_range %}
            {% if page_obj.number == p %}
              <li class="page-item disabled"><a href="?page={{ p }}" class="page-link">{{ p }}</a></li>
            {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2  %}
              <li class="page-item">
                <a href="?page={{ p }}" class="page-link">{{ p }}</a>
              </li>
            {% endif %}
          {% endfor %}
          {% if page_obj.has_next %}
            <li class="page-item">
              <a href="?page={{ page_obj.next_page_number }}" class="page-link">&raquo;</a>
            </li>
          {% endif %}
        </ul>
        {% endif %}
    </nav>
   {% bootstrap_javascript %}
   <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
   <script type="text/JavaScript" src="{% static 'js/script.js' %}"></script> 
   <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
   <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
  </body>
</html>

idea/templates/idea/categories.html
{% extends "idea/base.html" %}

{% block content %}
    {% for cat in categories %}
    <p><a href="{% url 'category' cat.id %}">{{ cat.name }}</a><p>
    {% endfor %}
{% endblock content %}

idea/templates/idea/category.html
{% extends "idea/base.html" %}

{% block content %}
<div class="container py-3">
  <div class="row row-cols-1 row-cols-md-3 g-6">
      {% for i in ideas %}
        <div class="col">
          <div class="card border-dark mb-3 mx-auto p-2" style="width: 100%; height: 18rem; display: flex;">
            <div class="card-header card text-center">
              <h5>
                <a href="{{ i.get_absolute_url }}" class="link-dark link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover">
                  {{ i.title|truncatechars:30 }}
                </a>
              </h5>
            </div>
            <div class="card-body">
              <h4 class="card-text">{{ i.description|linebreaks|truncatechars:40 }}</h4>
            </div>
            <div class="card-footer bg-transparent text-center">
              <a href="{{ i.get_absolute_url }}">
                <button src="{{ i.get_absolute_url}}" type="button" class="btn btn-success">
                  Выполнить
                </button>
              </a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div> 
  </div>
{% endblock content %}

idea/templates/idea/change_password.html
{% extends "idea/base.html" %}

{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                            <div class="card-header justify-content-center">
                              <h3 class="font-weight-light my-4 text-center">Change Your Password</h3>
                            </div>
                            {% if form.errors %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <div id="form_errors">
                                        {% for key, value in form.errors.items %}
                                            <strong>{{ value }}</strong>
                                        {% endfor %}
                                    </div>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endif %}

                            <div class="card-body">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_old_password">Old Password</label>
                                                <input type="password" name="old_password" autocomplete="new-password"
                                                       class="form-control" required id="id_old_password"
                                                       placeholder="Enter Old Password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password1">New Password</label>
                                                <input type="password" name="new_password1" autocomplete="new-password"
                                                       class="form-control" required id="id_new_password1"
                                                       placeholder="Enter New Password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password2">New Password Confirmation</label>
                                                <input type="password" name="new_password2" autocomplete="new-password"
                                                       required id="id_new_password2" class="form-control"
                                                       placeholder="Confirm New Password"/>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group mt-0 mb-1">
                                                <button type="submit" class="col-md-12 btn btn-dark" id="reset">Update Password</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

idea/templates/idea/idea_detail.html
{% extends "idea/base.html" %}

{% block content %}
<div class="container">
    <p><h1>{{ idea.title }}</h1></p>
    <p>{{ idea.description }}</p>
    Автор: <a href="{% url 'profile' idea.author %}">{{ idea.author }}</a>
    <p>Категория: {{ idea.category }}</p>
    <form action="{% url 'add_comment' idea_id=idea.id %}" method="post">
        {% csrf_token %}
        <div class="mb-3" style="width: 30rem;">
            <label for="{{ form.text.id_for_label }}" class="form-label"></label>
            <textarea name="text" class="form-control" id="exampleFormControlTextarea" rows="3" placeholder="Оставить комментарий"></textarea>
          </div>
          <select name="score" class="form-select" style="width: 30rem;">
            <option selected>Оценка</option>
            {% for value, label in score %}
            <option value="{{ value }}">{{ label }}</option>
        {% endfor %}
          </select>
        <button type="submit" class="btn btn-dark" style="margin-top: 15px;">Отправить</button>
    </form>
    <div class="container my-5 py-5">
        <div class="row d-flex justify-content-center">
          <div class="col-md-12 col-lg-10 col-xl-8">
            <div class="card">
              <div class="card-body p-4">
                <h4 class="text-center mb-4 pb-2">Комментарии</h4>
                <div class="row">
                  <div class="col">
                    {% for comment in comments %}
                    <div class="d-flex flex-start">
                        {% if comment.author.avatar %}
                        <img class="rounded-circle shadow-1-strong me-3" 
                        src="{{ comment.author.avatar.url }}" alt="avatar" width="65"
                        height="65">
                      {% else %}
                        <svg xmlns="http://www.w3.org/2000/svg" width="65"
                        height="65" fill="grey" class="bi bi-person-fill" viewBox="0 0 16 16">
                          <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
                        </svg>
                      {% endif %}
                      <div class="flex-grow-1 flex-shrink-1">
                        <div>
                          <div class="d-flex justify-content-between align-items-center">
                            <p class="mb-1">
                                    <strong>{{ comment.author }}</strong> <span class="small">- {{ comment.time_create|date:"d M Y" }} {{ comment.time_create|time:"H:i" }}
                                        ({{ comment.get_score_display }})
                                    </span>
                            </p>
                            <a href="#!"><i class="fas fa-reply fa-xs"></i><span class="small"> reply</span></a>
                          </div>
                          <p class="small mb-0">
                            {{ comment.text }}
                          </p>
                        </div>
                            </div>
                          </div>
                        {% endfor %}
                        </div>
                      </div>
                    </div>
                
                    
            </div>
{% endblock content %}

idea/templates/idea/index.html
{% extends "idea/base.html" %}

{% block content %}
<div class="container py-3">
  <div class="row row-cols-1 row-cols-md-3 g-6">
      {% for i in ideas %}
        <div class="col">
          <div class="card border-dark mb-3 mx-auto p-2" style="width: 415px; height: 18rem; display: flex;">
            <div class="card-header card text-center">
              <h5>
                <a href="{{ i.get_absolute_url }}" class="link-dark link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover">
                  {{ i.title|truncatechars:30 }}
                </a>
              </h5>
            </div>
            <div class="card-body">
              <h4 class="card-text">{{ i.description|linebreaks|truncatechars:40 }}</h4>
            </div>
            <div class="card-footer bg-transparent text-center">
              <a href="{{ i.get_absolute_url }}">
                <button src="{{ i.get_absolute_url}}" type="button" class="btn btn-success">
                  Выполнить
                </button>
              </a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div> 
  </div>
</div>

    
{% endblock content %}

idea/templates/idea/my_profile.html
{% extends "idea/base.html" %}

{% block content %}

{% if user.avatar %}
    <img src="{{ user.avatar.url }}" alt="mdo" width="230" height="230" class="rounded-circle">
{% else %}
    <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="white" class="bi bi-person-fill" viewBox="0 0 16 16">
    <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
    </svg>
{% endif %}
{{ user.username }}
{{ user.first_name }}
{{ user.last_name }}
{{ user.email }}

{% endblock content %}